### ISSUE TITLE
Blender 2.9 Breaks CATS Pose Mode

### ISSUE THREAD

**Issue by ThePoliticalGamer** [GiveMeAllYourCats/cats-blender-plugin#206]
OS: Windows 10
Downloader: Steam
Blender Version: 2.90.0

Issue: On a clean install of Blender with only a clean download of CATS installed using Post to Shape Key or Apply as Rest Pose results in `TypeError: Converting py args to operator properties: : keyword "apply_as" unrecognized` and the edits are not applied

Full Shape Key error:

```
Traceback (most recent call last):
  File "C:\Users\Jessica\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\cats-blender-plugin-master\tools\armature_manual.py", line 285, in execute
    pose_to_shapekey('PoseToRest')
  File "C:\Users\Jessica\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\cats-blender-plugin-master\tools\armature_manual.py", line 193, in pose_to_shapekey
    bpy.ops.object.modifier_apply(apply_as='SHAPE', modifier=mod.name)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.90\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "apply_as" unrecognized

location: <unknown location>:-1
```

Full Post to Rest error: 

```
Traceback (most recent call last):
  File "C:\Users\Jessica\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\cats-blender-plugin-master\tools\armature_manual.py", line 285, in execute
    pose_to_shapekey('PoseToRest')
  File "C:\Users\Jessica\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\cats-blender-plugin-master\tools\armature_manual.py", line 193, in pose_to_shapekey
    bpy.ops.object.modifier_apply(apply_as='SHAPE', modifier=mod.name)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.90\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "apply_as" unrecognized

location: <unknown location>:-1
```

Image of error log: https://cdn.discordapp.com/attachments/663032978175426591/750349817107972166/Capture.PNG

**Comment by sup3rflyn1nja** [comment]
I have the same issue on "Apply as Rest Pose"
```
Traceback (most recent call last):
  File "C:\Users\acp_s\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\cats-blender-plugin-master\tools\armature_manual.py", line 285, in execute
    pose_to_shapekey('PoseToRest')
  File "C:\Users\acp_s\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\cats-blender-plugin-master\tools\armature_manual.py", line 193, in pose_to_shapekey
    bpy.ops.object.modifier_apply(apply_as='SHAPE', modifier=mod.name)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.90\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "apply_as" unrecognized

location: <unknown location>:-1


```

**Comment by darklazer12** [comment]
Yes this issue happens when you use blender 2.9
But there a different way to apply rest pose
1. https://gyazo.com/30e14422da06e3dd3e7200329bda2d31  (You might have problems applying modifiers) 
2. https://gyazo.com/4e51a1653ef70fd98d54eaba558ed6a8 
3. You can download blender 2.8 and wait till cat plugin gets fixed https://download.blender.org/release/

**Comment by Darkblader24** [comment]
I already fixed it in the dev version, you can update to it via the build-in updater

**Comment by IAmVensey** [comment]
Hello! It looks like this might still be an issue, at least for me it is. I'm in Blender 2.9, and receiving an error like the one listed above. Is there a specific update to which I need to be set, or just the most recent one? My updater says I'm up to date, so I'm trying to figure out what else I can do to solve the issue.

**Comment by sup3rflyn1nja** [comment]
> Hello! It looks like this might still be an issue, at least for me it is. I'm in Blender 2.9, and receiving an error like the one listed above. Is there a specific update to which I need to be set, or just the most recent one? My updater says I'm up to date, so I'm trying to figure out what else I can do to solve the issue.

Hello IAmVensey, in the Cats Blender Plugin, if you go down towards the bottom you can see a "Dev" option or something like that. Hit the check mark and reset blender and it should work. Darkblader24 already mentioned that he fixed this issue in the dev version.

**Comment by IDarky** [comment]
> I already fixed it in the dev version, you can update to it via the build-in updater

@Darkblader24  Thanks for me  it fixed the problem.
@IAmVensey  I used 2.90.1
