### ISSUE TITLE
Atlassing errors

### ISSUE THREAD

**Issue by PiXel214** [GiveMeAllYourCats/cats-blender-plugin#219]
_Hello_ 
I've recently been trying to atlas the textures
 of my avatar that i made but I keep getting this error..

--------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\senne\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\material-combiner-addon-master\operators\combiner\combiner.py", line 29, in execute
    atlas = get_atlas(scn, self.structure, size)
  File "C:\Users\senne\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\material-combiner-addon-master\operators\combiner\combiner_ops.py", line 192, in get_atlas
    img.paste(get_gfx(scn, mat, i, i['gfx']['img']), (i['gfx']['fit']['x'] + int(scn.smc_gaps / 2),
  File "C:\Users\senne\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\material-combiner-addon-master\operators\combiner\combiner_ops.py", line 156, in get_gfx
    img = Image.open(src).convert('RGBA')
  File "C:\Users\senne\AppData\Roaming\Python\Python37\site-packages\PIL\Image.py", line 2944, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file 'C:\\Users\\senne\\3D Objects\\Ears&Tail\\tex\\body2.png'

location: <unknown location>:-1

--------------------------------------------------------------------------------------------------------------------------------------
Hopefully you can help!

**Comment by strawbnyeko** [comment]
I'm not sure if you're still here, but could you tell me how you fixed the issue?
