### ISSUE TITLE
Fix Model & Start Pose Mode Error Blender 2.82a

### ISSUE THREAD

**Issue by eldarstorm** [GiveMeAllYourCats/cats-blender-plugin#222]
Using Blender 2.82a Tested with both CATS 0.17.0 and 0.14.1-dev with same result.

I have a MMD model that I had saved from when I used Blender 2.79. 
When using Fix Model or Start Pose mode, I get a error. 

I only get these errors when using CATS in Blender 2.82a, when opening the same file in Blender 2.79 both options work fine.

Fix Model Error:
```
Traceback (most recent call last):
  File "C:\Users\Eldar\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\cats-blender-plugin-master\tools\armature.py", line 446, in execute
    bpy.ops.pose.rot_clear()
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.pose.rot_clear.poll() failed, context is incorrect

location: <unknown location>:-1
```
Start Pose Error: 
```
Traceback (most recent call last):
  File "C:\Users\Eldar\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\cats-blender-plugin-master\tools\armature_manual.py", line 82, in execute
    bpy.ops.pose.rot_clear()
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.pose.rot_clear.poll() failed, context is incorrect

location: <unknown location>:-1
```

**Comment by Darkblader24** [comment]
Could you send me that blend file in which this error occurs? It would allow me to replicate that error which makes it easier to fix.

**Comment by eldarstorm** [comment]
[Blake_Bomber_Jacket6.zip](https://github.com/GiveMeAllYourCats/cats-blender-plugin/files/5497521/Blake_Bomber_Jacket6.zip)

**Comment by Darkblader24** [comment]
Works fine for me on the dev version of cats now, give it another try.
