### ISSUE TITLE
Issue on linux while importing Cats

### ISSUE THREAD

**Issue by MCWertGaming** [GiveMeAllYourCats/cats-blender-plugin#268]
When I try to import the cats plugins on linux, i get the following error:
```
Traceback (most recent call last):
  File "/usr/share/blender/2.92/scripts/startup/bl_operators/userpref.py", line 694, in execute
    file_to_extract.extractall(path_addons)
  File "/usr/lib/python3.9/zipfile.py", line 1633, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/usr/lib/python3.9/zipfile.py", line 1687, in _extract_member
    open(targetpath, "wb") as target:
UnicodeEncodeError: 'ascii' codec can't encode character '\u2661' in position 109: ordinal not in range(128)
```
Seems like some update of either python or blender broke it. I'm running python 3.9.2 with blender 2.92.0 on archlinux. Is the problem really caused by an update or am I just using wrong components?

Thank you for your time!

**Comment by feilen** [comment]
Just to verify, your, $HOME/.config/blender/<ver>/ directory doesn't have any non-ascii characters in it does it?

**Comment by MCWertGaming** [comment]
No, I have installed blender and after that just tried to import cats, so everything should be just the default configurations.

**Comment by golden-ghostX** [comment]
you need to install MMD tools 
following this video
https://www.youtube.com/watch?v=NtPSo7xPIkM

**Comment by MCWertGaming** [comment]
After adding MMD tools cats shows in my add ons list in blender but I can't enble it. The console shows the same error as before:

```
Traceback (most recent call last):
  File "/usr/share/blender/2.92/scripts/startup/bl_operators/userpref.py", line 694, in execute
    file_to_extract.extractall(path_addons)
  File "/usr/lib/python3.9/zipfile.py", line 1633, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/usr/lib/python3.9/zipfile.py", line 1687, in _extract_member
    open(targetpath, "wb") as target:
UnicodeEncodeError: 'ascii' codec can't encode character '\u2661' in position 96: ordinal not in range(128)
```

**Comment by Darkblader24** [comment]
Blender should come bundled with Python, maybe give that a try instead of using a custom Python installation
