### ISSUE TITLE
Translation index out of range

### ISSUE THREAD

**Issue by AllNightLonger** [GiveMeAllYourCats/cats-blender-plugin#269]
Trying to use CATS to auto translate shape keys and materials results in the following error. The old method of translation still works though.
```
Traceback (most recent call last):
  File "C:\Users\james\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\cats-blender-plugin-master\tools\translate.py", line 80, in execute
    update_dictionary(to_translate, translating_shapes=True, self=self)
  File "C:\Users\james\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\cats-blender-plugin-master\tools\translate.py", line 438, in update_dictionary
    translations = [translator.translate(text, lang_src='ja', lang_tgt='en').strip() for text in google_input]
  File "C:\Users\james\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\cats-blender-plugin-master\tools\translate.py", line 438, in <listcomp>
    translations = [translator.translate(text, lang_src='ja', lang_tgt='en').strip() for text in google_input]
  File "C:\Users\james\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\cats-blender-plugin-master\extern_tools\google_trans_new\google_trans_new.py", line 188, in translate
    raise e
  File "C:\Users\james\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\cats-blender-plugin-master\extern_tools\google_trans_new\google_trans_new.py", line 168, in translate
    sentence = sentence[0]
Indexlist index out of range

location: C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py:199
```

**Comment by wickles** [comment]
Old method does not work for me. Same error message.

**Comment by Darkblader24** [comment]
Hey, this is now fixed in the dev version of cats, you can update to it via the built-in update in Cats
