### ISSUE TITLE
Unable to import module

### ISSUE THREAD

**Issue by hattori-emi** [GiveMeAllYourCats/cats-blender-plugin#279]
cats-blender-plugin Release: 0.18.0
Blender version: 2.83.5
System: Ubuntu 20.10

Traceback (most recent call last):
  File "/usr/share/blender/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/hattoriemi/.config/blender/2.83/scripts/addons/cats-blender-plugin-0-18-0/__init__.py", line 63, in <module>
    import mmd_tools_local
  File "/home/hattoriemi/.config/blender/2.83/scripts/addons/cats-blender-plugin-0-18-0/extern_tools/mmd_tools_local/__init__.py", line 49, in <module>
    from . import properties
  File "/home/hattoriemi/.config/blender/2.83/scripts/addons/cats-blender-plugin-0-18-0/extern_tools/mmd_tools_local/properties/__init__.py", line 16, in <module>
    from . import (
  File "/home/hattoriemi/.config/blender/2.83/scripts/addons/cats-blender-plugin-0-18-0/extern_tools/mmd_tools_local/properties/root.py", line 12, in <module>
    from mmd_tools_local.core.sdef import FnSDEF
  File "/home/hattoriemi/.config/blender/2.83/scripts/addons/cats-blender-plugin-0-18-0/extern_tools/mmd_tools_local/core/sdef.py", line 4, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by Darkblader24** [comment]
Somehow your Blender is using a different Python than the in it comes bundled with. Check if you have a custom Python version installed and try removing it from the system enviroment variables
