### ISSUE TITLE
BUG?----blender 2.93

### ISSUE THREAD

**Issue by qidou233** [GiveMeAllYourCats/cats-blender-plugin#282]
[![2tAKK0.png](https://z3.ax1x.com/2021/06/05/2tAKK0.png)](https://imgtu.com/i/2tAKK0)

**Comment by FangyBat** [comment]
I'm getting the exact same problem. 

> Traceback (most recent call last):
  File "C:\Users\rouge\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-master\extern_tools\mmd_tools_local\operators\fileio.py", line 159, in execute
    self.__translator = DictionaryEnum.get_translator(self.dictionary)
  File "C:\Users\rouge\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-master\extern_tools\mmd_tools_local\translations.py", line 323, in get_translator
    return getTranslator(dictionary)
  File "C:\Users\rouge\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-master\extern_tools\mmd_tools_local\translations.py", line 171, in getTranslator
    elif csvfile in bpy.data.texts:
TypeError: bpy_prop_collection.__contains__: expected a string or a tuple of strings

**Comment by a457872681** [comment]
我也一样

**Comment by windskyxb** [comment]
I have the same problem

**Comment by Da-Nuker** [comment]
If you are on 2.93, go to the addon and click "Install Development Version". This will install the 0.18.1-dev version and it should work.work:

![image](https://user-images.githubusercontent.com/30483443/123039145-2fc0ae80-d424-11eb-9216-3c104a70e673.png)

**Comment by Darkblader24** [comment]
Thank you for the reports, this is now fixed in the new release version 0.19.0.
