### ISSUE TITLE
Error when importing pmx

### ISSUE THREAD

**Issue by lurkingaround** [GiveMeAllYourCats/cats-blender-plugin#296]
First time using this so not sure what's happening and whether it's my fault but here's the error log.
```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-0-19-0\extern_tools\mmd_tools_local\operators\fileio.py", line 163, in execute
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-0-19-0\extern_tools\mmd_tools_local\operators\fileio.py", line 182, in _do_execute
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-0-19-0\extern_tools\mmd_tools_local\core\pmx\importer.py", line 839, in execute
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-0-19-0\extern_tools\mmd_tools_local\core\pmx\importer.py", line 79, in __createObjects
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-0-19-0\extern_tools\mmd_tools_local\core\model.py", line 69, in create
AttributeError: 'Object' object has no attribute 'mmd_type'
```

**Comment by ZarephLae** [comment]
I have same issue
