### ISSUE TITLE
CATS unable to import MMD model

### ISSUE THREAD

**Issue by ZarephLae** [GiveMeAllYourCats/cats-blender-plugin#310]
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\cats-blender-plugin-master\tools\importer.py", line 100, in execute
    self.import_file(self.directory, file_name)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\cats-blender-plugin-master\tools\importer.py", line 141, in import_file
    bpy.ops.mmd_tools.import_model('EXEC_DEFAULT',
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\bpy\ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\cats-blender-plugin-master\extern_tools\mmd_tools_local\operators\fileio.py", line 163, in execute
    self._do_execute(context)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\cats-blender-plugin-master\extern_tools\mmd_tools_local\operators\fileio.py", line 182, in _do_execute
    importer_cls().execute(
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\cats-blender-plugin-master\extern_tools\mmd_tools_local\core\pmx\importer.py", line 839, in execute
    self.__createObjects()
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\cats-blender-plugin-master\extern_tools\mmd_tools_local\core\pmx\importer.py", line 79, in __createObjects
    self.__rig = mmd_model.Model.create(pmxModel.name, pmxModel.name_e, self.__scale, obj_name)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\cats-blender-plugin-master\extern_tools\mmd_tools_local\core\model.py", line 69, in create
    root.mmd_type = 'ROOT'
AttributeError: 'Object' object has no attribute 'mmd_type'

location: <unknown location>:-1

I am not the only person with this issue. I have seen posts from a month to months ago unanswered.

**Comment by boboshu** [comment]
me too

**Comment by Nambers** [comment]
in my case, after reopened Blender, this error disappeared

**Comment by leenldk** [comment]
The problem may caused by incompatibility with blender 3.x version. The problem is sloved when switch to blender 2.93.1 LTS version.

**Comment by DRSalieri** [comment]
I restart my blender and then fixed this.

**Comment by GengGode** [comment]
It seems that it will be OK after restart

**Comment by Hutao99999** [comment]
Try restart blender
